docker-compose.yml
frontend/.nuxt/index.js
frontend/.nuxt/router.js
frontend/Dockerfile
frontend/pages/user/edit.vue

`docker-compose.yml`と`Dockerfile`のディレクトリの指定が間違っていたので変更しました。
あと、全部のファイルをfrontコンテナにマウントされていたので、frontendディレクトリのみコンテナにマウントするようにしました
`frontのコンテナ/frontend`

#44 ホットリロード可能

---

docker-compose.yml

docker-compose upコマンドでnuxtも立ち上がるように修正

---

README.md

Update Readme 環境構築の手順を追加

---

frontend/layouts/default.vue
frontend/pages/user/_id.vue
frontend/pages/user/edit/_id.vue
frontend/pages/user/login.vue
frontend/pages/user/sign_up.vue
frontend/store/index.js

- $axios.defaults.baseURLの削除
nuxt.config.jsでaxios.baseURLを設定した場合、自動でbaseURLが挿入されるため。
- v-bind, v-onを省略形に統一。

#56 refactor2

---

.vscode/settings.json

プロジェクト内のSettings.jsonに追加しました。
``` json
"eslint.autoFixOnSave": true,
"editor.codeActionsOnSave": {
"source.fixAll.eslint": true
}
```

プロジェクト内のsettings.jsonに追加

---

.circleci/config.yml

- やったこと
node_modules削除のフローを追加してキャッシュが残らないようにした

node_modulesを削除する

---

frontend/components/atoms/btns/OrangeBtn.vue
frontend/components/molecules/btns/GithubBtn.vue
frontend/components/molecules/btns/GoogleBtn.vue
frontend/components/molecules/btns/TwitterBtn.vue
frontend/components/organisms/btnGroup/LoginSnsBtnGroup.vue
frontend/components/organisms/btnGroup/UserSnsBtnGroup.vue
frontend/components/organisms/cards/SigninCard.vue
frontend/components/organisms/form/SinginForm.vue
frontend/components/organisms/textFields/EmailTextField.vue
frontend/components/organisms/textFields/PasswordTextField.vue
frontend/components/organisms/textFields/UsernameTextField.vue
frontend/components/templates/SigninTemplate.vue

各コンポーネントを作成し`/signin`を実装した
途中からissueの番号間違えました。

/signinの作成

---

frontend/assets/json/Sidebar.json
frontend/components/organisms/cards/SettingProfileCard.vue
frontend/components/organisms/form/EditProfileForm.vue
frontend/components/templates/SettingProfileTemplate.vue
frontend/pages/settings/profile.vue

`settings/profile`の処理を作成
usernameとnameがかぶるため、usernameを変更するためのページを別に作成するよう変更

プロフィール変更の保存処理を作成

---

frontend/components/molecules/containers/OneColumnContainer.vue
frontend/components/molecules/containers/TwoColumnContainer.vue
frontend/components/organisms/sidebar/GuestSidebar.vue
frontend/components/organisms/sidebar/LoginSidebar.vue
frontend/jest.config.js
frontend/src/domain/models/sidebarModel.js
frontend/src/domain/services/sidebarService.js
frontend/src/infra/sidebarJsonInfra.js
frontend/tests/utils/sidebar.spec.js

- サイドバーの場所を変更
- サイドバーをクラスにした(レイヤードアーキテクチャをイメージした)
- Containerにpropsを追加

サイドバーの場所を変更とContainerの修正

---

app/models/user.rb

userモデルのメソッドの位置をわかりやすくした
・アソシエーション関連とバリデーション関連のメソッドの位置を分けた。

モデルのメソッドの位置をまとめた。

---

frontend/components/organisms/cards/ChangeUsernameCard.vue
frontend/components/organisms/form/ChangeUsernameForm.vue
frontend/components/organisms/textFields/UsernameTextField.vue
frontend/components/templates/SigninEnterusernameTemplate.vue
frontend/pages/signup/enter-user-name.vue

/enter-user-nameページの作成

---

frontend/components/organisms/fileInputs/BaseImageFileInput.vue
frontend/components/organisms/fileInputs/PreviewImageFileInput.vue
frontend/components/organisms/form/EditProfileForm.vue

急遽バックエンドの検証のためファイルアップロード機能が必要みたいなのでこの部分だけ実装しました。プレビューなどは違うブランチで実装します

ファイルアップロード機能の実装

---

frontend/pages/settings/profile.vue

avatarを送信【修正】

---

frontend/package-lock.json
frontend/package.json
frontend/store/authentication.js
frontend/store/index.js
frontend/tests/store/authentication.spec.js

- state.isAuthenticatedを削った
isAuthenticatedの判定はuidがあるかどうかなので、stateを削って、gettersでuidがあるかで判定するようにした
- いくつか、命名の変更
- Cookieのライブラリを変更
universal-cookieを使用することにした(#81)

#81 Storeの処理を修正とCookieのライブラリを変更

---

frontend/components/organisms/fileInputs/BaseImageFileInput.vue
frontend/components/organisms/form/EditProfileForm.vue
frontend/pages/settings/profile.vue

プロフィールページのエラーの修正

---

frontend/components/organisms/form/EditProfileForm.vue

#135 の
> ActiveSupport::MessageVerifier::InvalidSignatureというエラーが出ている。
を解決

issue #135 の解決

---

frontend/components/molecules/containers/TwoColumnContainer.vue

fix TwoColumnContainer Propsのdefault値を間違えていた

---

frontend/assets/json/Sidebar.json
frontend/components/molecules/btns/TwitterShareBtn.vue
frontend/components/organisms/markdown/EditMarkdown.vue
frontend/components/organisms/textFields/FileNameTextField.vue
frontend/components/templates/EditFileidSuccessTemplate.vue
frontend/components/templates/EditFileidTemplate.vue
frontend/pages/edit/_fileID.vue
frontend/pages/edit/new.vue
frontend/pages/edit/success.vue
frontend/utils/fileID.js
frontend/utils/string.js

- ` /edit/new (新規TIL作成) `と`/edit/${fileID} (既存TIL更新)`の追加
- Twitterへの投稿 (/edit/success)
- 422エラーの取り扱い
- store周り (postのデータをstoreであつかうかどうかは、#169 が完成してから考える。)

feat TILの更新をできるようにした

---

frontend/assets/sass/common.scss
frontend/components/organisms/cards/SigninCard.vue
frontend/components/organisms/cards/SignupCard.vue
frontend/components/organisms/form/SigninForm.vue
frontend/components/organisms/form/SignupForm.vue
frontend/components/templates/SigninTemplate.vue
frontend/components/templates/SignupTemplate.vue
frontend/middleware/check-cookie-integrity.js
frontend/nuxt.config.js
frontend/pages/signin/index.vue
frontend/pages/signup/index.vue
frontend/store/index.js
frontend/utils/cookie.js

- singin, singupのデザインの修正
- Cookieの不整合の解決
ログイン(新規作成)の空白を削ったりしたので、微妙になったところは言うか、別で修正したほしいです。

refactor デザインの修正とCookieの不整合の解決(#164 )

---

frontend/components/organisms/list/FileFolderListWithAction.vue
frontend/components/templates/UsernameIndexTemplate.vue
frontend/pages/_username/_.vue
frontend/pages/signup/index.vue

- 新規登録成功時に正常に画面が切り替わるようにした
- v-elseやidの指定がうまくできていなかったのでなおした。(frontend/components/organisms/list/FileFolderListWithAction.vue)

fix 新規登録成功時に正常に画面が切り替わるようにした

---

frontend/components/organisms/breadcrumbs/FolderBreadcrumbs.vue
frontend/components/organisms/cards/UserIntroCard.vue
frontend/components/organisms/list/FileFolderListWithAction.vue
frontend/components/organisms/list/LinkToBackItem.vue
frontend/components/templates/UsernameIndexTemplate.vue
frontend/pages/_username/_.vue
frontend/pages/_username/index.vue

- どのユーザからでも各ユーザのマイページ見れるように変更
- パンくずリストの実装
- フォルダバックの実装方法変更

パンくずリストとフォルダバックの実装

---

frontend/components/templates/AboutIndexTemplate.vue
frontend/nuxt.config.js

PCのデザインの見た目に変化はなし。
スマホで写真が崩れたり、タイトルが改行されないようにした
pwaの設定もした
縦長で見にくいから、リンクにした
https://user-images.githubusercontent.com/46477357/84996310-0b365480-b188-11ea-9248-33a064d16b63.png

design /aboutのデザインを修正

---

frontend/components/organisms/header/HeaderContainer.vue
frontend/components/organisms/sidebar/SidebarContainer.vue
frontend/components/organisms/sidebar/TheSidebar.vue
frontend/components/organisms/textFields/PasswordTextField.vue
frontend/layouts/default.vue
frontend/nuxt.config.js
frontend/store/sidebar.js

- cdn関連をローカルのキャッシュに入れた
- サイドバーが正常に開閉できるように改善
- サイトマップの設定をした
サイドバーの変数をバケツリレーで管理したかったが、この方式だとバグが見つからなかった。
だから、vuexで処理を書き直したらうまく行った

perf サイドバーの挙動改善とキャッシュの設定

---

frontend/assets/json/Sidebar.json
frontend/components/organisms/list/HomeSidebarListItem.vue

fix SidebarItem。変数がリアクティブになるようにした

---

frontend/components/organisms/cards/ChangeUsernameCard.vue
frontend/components/templates/SettingsUserNameTemplate.vue
frontend/pages/settings/user-name.vue
frontend/pages/signin/index.vue
frontend/pages/signup/enter-user-name.vue

初めてのログイン時にusernameを編集する画面に遷移するようにした

feat 新規登録時の流れを修正  #206

---

frontend/assets/sass/common.scss
frontend/components/organisms/form/EditProfileForm.vue
frontend/components/organisms/text/ProverbText.vue
frontend/components/templates/EditPostSuccessTemplate.vue
frontend/components/templates/EditPostTemplate.vue
frontend/components/templates/UsernamePostTemplate.vue
frontend/nuxt.config.js
frontend/tests/utils/Proverb.spec.js
frontend/utils/Proverb.js
frontend/utils/number.js

- 格言のデザインの作成
- パフォーマンスのために、キャッシュにいろいろ突っ込んだ
- あとは、デザインの崩れを修正

feat 格言のデザインの作成

---

frontend/components/organisms/footer/TheFooter.vue
frontend/layouts/default.vue

fix: マイページはフッターを非表示に変更

---

frontend/components/templates/UsernameFolderTemplate.vue
frontend/pages/_username/_.vue
frontend/pages/_username/index.vue
frontend/tests/middleware/authenticated.spec.js
frontend/tests/middleware/check-auth.spec.js
frontend/tests/middleware/guest.spec.js
frontend/tests/utils/number.spec.js
frontend/utils/Proverb.js
frontend/utils/number.js

- Middleware (Auth, Guest, check-auth)のテストの追加
- ランド関数の修正とテスト
- マイページのURLバリデーションのリファクタ
- パンくずの名前がnullになるのを修正

test & refactor middlewareのテスト追加とマイページのURLバリデーションのリファクタ

---

frontend/package-lock.json
frontend/package.json
frontend/tests/utils/number.spec.js

- フロントのバージョン上げ
- constをletに修正 (test)

Chore フロントのversionを挙げた

---

frontend/components/organisms/cards/SidebarUserCard.vue

fix サイドバーのUserCardの崩れを修正
